### ISSUE TITLE
bug in manhattan_plot function

### ISSUE THREAD

**Issue by rjcorb** [steibelj/gwaR#1]
In line 128 of R/additional.R, chromosomes are converted to factors before being coerced into numeric values, shuffling the chromosomes and rendering the function unusable.

**Comment by steibelj** [comment]
Thank you Ryan for picking this up. I will fix and reupload 


Sent from my Verizon 4G LTE smartphone

-------- Original message --------

**Comment by steibelj** [comment]
It should be fixed by now, Ryan. you will have to re-install


JP
